# Generated by Django 4.2.4 on 2023-08-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import guardapp.validators
import residentapp.validators
import rootapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('floor', models.CharField(choices=[('Ground', 'Ground'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], default='1st', max_length=6)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Guards monthly payment')),
                ('guard_id', models.CharField(default='GA-', max_length=10, validators=[guardapp.validators.guard_id_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=7)),
                ('nid_or_br', models.CharField(max_length=20, verbose_name='National identity card or Birth registration No.')),
                ('contact', models.CharField(max_length=11, verbose_name='Phone number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('photo', models.ImageField(upload_to='human')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='the_human', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(default='RS-', max_length=10, validators=[residentapp.validators.resident_id_validator])),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_here', to='rootapp.block')),
                ('human', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='the_resident', to='rootapp.human')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=12, unique=True, validators=[rootapp.validators.token_validator])),
                ('nag', models.PositiveSmallIntegerField(default=1, verbose_name='Number of allowed guests')),
                ('nou', models.PositiveSmallIntegerField(default=0, verbose_name='Number of guests used this token')),
                ('used', models.BooleanField(default=False)),
                ('valid_till', models.DateTimeField(auto_now=True)),
                ('fond_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gained_tokens', to='rootapp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_type', models.CharField(choices=[('Entry', 'Entry'), ('Exit', 'Exit')], default='Entry', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_records', to='rootapp.guard')),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='rootapp.human')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Problem title')),
                ('details', models.TextField(verbose_name='Problem in details')),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False, verbose_name='Checked by admin')),
                ('resolved', models.BooleanField(default=False, verbose_name='Admin taken necessary steps to resolve this issue')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rootapp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(default='GS-', max_length=10, unique=True, validators=[rootapp.validators.guest_id_validator])),
                ('photo', models.ImageField(upload_to='guests')),
                ('nid_or_br', models.CharField(max_length=32, verbose_name='National Identity/Birth Registration No.')),
                ('guest_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='rootapp.resident')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='rootapp.token')),
            ],
        ),
        migrations.AddField(
            model_name='guard',
            name='human',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='the_guard', to='rootapp.human'),
        ),
        migrations.AddField(
            model_name='block',
            name='doer_resident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lives_in', to='rootapp.resident'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Bill's description")),
                ('tnx_nmr', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction number')),
                ('bill_type', models.CharField(choices=[('RENT', 'ROOM RENT'), ('WATER', 'WATER'), ('ELECTRICITY', 'ELECTRICITY'), ('WASTE DISPOSAL', 'WASTE DISPOSAL'), ('SECURITY', 'SECURITY'), ('PARKING', 'PARKING'), ('OTHER', 'OTHER')], default='RENT', max_length=14, verbose_name='Bill for which')),
                ('amount', models.PositiveIntegerField(verbose_name='Payable amount')),
                ('granted', models.BooleanField(default=False, verbose_name='Granted-? (admin only)')),
                ('billed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='rootapp.resident')),
            ],
        ),
    ]
