# Generated by Django 4.2.4 on 2023-09-12 07:25

from django.db import migrations, models
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_alter_human_options_issue_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='12666053DB6C', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
    ]
