# Generated by Django 4.2.4 on 2023-09-17 00:54

from django.db import migrations, models
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0003_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='1266609F208B', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
    ]
