# Generated by Django 4.2.4 on 2023-10-16 07:01

from django.db import migrations, models
import django.db.models.deletion
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0004_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='his_her_entries', to='rootapp.resident'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='12666686BBF3', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
    ]
