# Generated by Django 4.2.4 on 2023-10-22 16:51

from django.db import migrations, models
import django.db.models.deletion
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0007_alter_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='126666E3BC9D', max_length=12, unique=True, validators=[rootapp.validators.token_validator])),
                ('nag', models.PositiveSmallIntegerField(default=1, verbose_name='Number of allowed guests')),
                ('nou', models.PositiveSmallIntegerField(default=0, verbose_name='Number of guests used this token')),
                ('used', models.BooleanField(default=False)),
                ('valid_till', models.DateTimeField(auto_now=True)),
                ('fond_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gained_tokens', to='rootapp.resident')),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='rootapp.temptoken'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
