# Generated by Django 4.2.4 on 2023-10-22 16:52

from django.db import migrations, models
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0008_temptoken_alter_guest_token_delete_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptoken',
            name='token',
        ),
        migrations.AddField(
            model_name='temptoken',
            name='key',
            field=models.CharField(default='126666E3BCE5', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
    ]
