# Generated by Django 4.2.4 on 2023-10-22 17:33

from django.db import migrations, models
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0009_remove_temptoken_token_temptoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptoken',
            name='key',
            field=models.CharField(default='126666E3DC7C', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
    ]
