# Generated by Django 4.2.4 on 2023-10-22 17:35

from django.db import migrations, models
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0010_alter_temptoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptoken',
            name='key',
            field=models.CharField(default='126666E3DD57', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
        migrations.AlterField(
            model_name='temptoken',
            name='valid_till',
            field=models.DateTimeField(),
        ),
    ]
