# Generated by Django 4.2.4 on 2023-10-22 17:38

from django.db import migrations, models
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0011_alter_temptoken_key_alter_temptoken_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptoken',
            name='key',
            field=models.CharField(default='126666E3DE94', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
    ]
