# Generated by Django 4.2.4 on 2023-10-23 09:08

from django.db import migrations, models
import rootapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0013_alter_temptoken_key_alter_temptoken_nag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptoken',
            name='key',
            field=models.CharField(default='126666F1DC93', max_length=12, unique=True, validators=[rootapp.validators.token_validator]),
        ),
        migrations.AlterField(
            model_name='temptoken',
            name='nag',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of allowed guests'),
        ),
    ]
